// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Statistic struct {
	ID        int32              `json:"id"`
	UserID    string             `json:"user_id"`
	Count     int64              `json:"count"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
